version: '3.8'

services:
  backend:
    build: ./backend
    container_name: luna25_submission
    restart: always
    environment:
      MODEL_PATH: "/opt/app/resources/I3D-20251215/best_metric_model.pth"
    ports:
      - "5000:5000"
    
    volumes:
       - ./backend/uploads:/opt/app/uploads